language: generic

notifications:
  email: false

# Blacklist
branches:
  only:
    - master
#  except:
#    - /^*-v[0-9]/

# Environment variables
#env:
#  global:
#    - GH_REPO_NAME: tModLoader
#    - DOXYFILE: $TRAVIS_BUILD_DIR/solutions/documentation/Doxyfile
#    - GH_REPO_REF: github.com/bluemagic123/tModLoader.git
     
# all runs, check latest, abort
# 1st run will generate tag by automatically checking latest mod browser version.
# if exists, it creates tag and deploy isn't run this time, it not exists, creats tag, success.
# 2nd run will download, deploy

# Build your code e.g. by calling make
script:
  - pwd
  - ls
  - git tag
  - cd $TRAVIS_BUILD_DIR
  - ls
  - chmod +x travisScript.sh
  - ./travisScript.sh
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - export GIT_TAG=`curl http://javid.ddns.net/tModLoader/tools/latestmodversionsimple.php?modname=BossChecklist`
#  - export GIT_TAG=v0.1.1.6.4
#  - git tag $GIT_TAG -a -m "TravisCI Autogenerated Tag"
#  - git push --quiet https://$GH_REPO_TOKEN@github.com/JavidPack/BossChecklist $GIT_TAG > /dev/null 2>&1
  
#  - download mod, check latest version
# return non zero to fail
before_deploy:
  - wget -O BossChecklist.tmod http://javid.ddns.net/tModLoader/download.php?Down=mods/BossChecklist.tmod
  - ls
  
# Generate and deploy documentation
after_success:
  - echo "after_success"
  # CREATE GIT TAG
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "Travis CI"
#  - export GIT_TAG=v0.1.1.6.1
#  - echo -n $GIT_TAG > public/version
#  - git commit -m "Set build VERSION number" public/version
#  - git tag $GIT_TAG -a -m "TravisCI Autogenerated Tag"
#  - git push --quiet https://$GH_REPO_TOKEN@github.com/JavidPack/BossChecklist $GIT_TAG > /dev/null 2>&1



deploy:
  provider: releases
  api_key: $GH_REPO_TOKEN
  file: "BossChecklist.tmod"
  skip_cleanup: true
  on:
    tags: false