language: generic

notifications:
  email: false

branches:
  only:
    - master

# Environment variables
env:
  global:
    - MODNAME: BossChecklist
    - NEEDDEPLOY: DOESNOTNEEDDEPLOY
    
script:
  - pwd
  - ls
  - git tag
  - cd $TRAVIS_BUILD_DIR
  - ls
  - chmod +x AutoReleaseFromModBrowser.sh
  # fails if mod browser version already released to github
  - ./AutoReleaseFromModBrowser.sh
  - echo "NEEDDEPLOY is $NEEDDEPLOY"

before_deploy:
  - wget -O $MODNAME.tmod http://javid.ddns.net/tModLoader/download.php?Down=mods/$MODNAME.tmod
  - ls

# should only deploy if the script doesn't fail, meaning we have a new .tmod file to publish
deploy:
  provider: releases
  api_key: $GH_REPO_TOKEN
  file: "$MODNAME.tmod"
  skip_cleanup: true
  on:
    tags: false
    condition: "$NEEDDEPLOY = NEEDSDEPLOY"