language: c

notifications:
  email: false

# Blacklist
branches:
  only:
    - master
  except:
    - /^*-v[0-9]/

# Environment variables
#env:
#  global:
#    - GH_REPO_NAME: tModLoader
#    - DOXYFILE: $TRAVIS_BUILD_DIR/solutions/documentation/Doxyfile
#    - GH_REPO_REF: github.com/bluemagic123/tModLoader.git
     
# Build your code e.g. by calling make
script:
  - pwd
  - ls
  - git tag
  
#  - download mod, check latest version
# return non zero to fail
  
# Generate and deploy documentation
after_success:
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=v0.1.1.7
#  - echo -n $GIT_TAG > public/version
#  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG
  - git push --quiet https://$GH_REPO_TOKEN@github.com/JavidPack/BossChecklist $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true